# Generated by Django 6.0.4 on 2026-05-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=100)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("Factory", "Factory Orders"),
                            ("Customer", "Customer Orders"),
                            ("PD", "PD Orders"),
                            ("Repair", "Repair Orders"),
                            ("Sample", "Sample Orders"),
                            ("RD", "R&D Orders"),
                            ("ICO", "ICO Orders"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Necklace Set", "Necklace Set"),
                            ("Necklace", "Necklace"),
                            ("Earrings", "Earrings"),
                            ("Pendant Set", "Pendant Set"),
                            ("Pendant", "Pendant"),
                            ("Rings", "Rings"),
                            ("Bracelets", "Bracelets"),
                            ("Bangle", "Bangle"),
                            ("Accessories", "Accessories"),
                        ],
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("start_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_name", models.CharField(max_length=100)),
                ("sla_days", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.order"
                    ),
                ),
            ],
        ),
    ]
