# Generated by Django 6.0.4 on 2026-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_end_date_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="style_type",
            field=models.CharField(
                choices=[("New", "New Style"), ("Repeat", "Repeat Style")],
                default="New",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="category",
            field=models.CharField(
                choices=[
                    ("Necklace Set", "Necklace Set"),
                    ("Necklace", "Necklace (Standalone)"),
                    ("Earrings", "Earrings"),
                    ("Pendant Set", "Pendant Set"),
                    ("Pendant", "Pendant (Standalone)"),
                    ("Rings", "Rings"),
                    ("Bracelets", "Bracelets"),
                    ("Bangle", "Bangle"),
                    ("Accessories", "Accessories"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("Factory", "Factory Orders – Stock Replenishment"),
                    ("Customer", "Customer Orders – confirmed customer order"),
                    ("PD", "PD Orders – New Product Development"),
                    ("Repair", "Repair Orders – Repair/Rework items"),
                    ("Sample", "Sample Orders – Stock in alloy with CZ"),
                    ("RD", "R&D Orders – Research & Development"),
                    (
                        "ICO",
                        "ICO Orders – Immediate Customer Orders (urgent execution)",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
